# Form implementation generated from reading ui file 'profile_import_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ProfileImportDialog(object):
    def setupUi(self, ProfileImportDialog):
        ProfileImportDialog.setObjectName("ProfileImportDialog")
        ProfileImportDialog.resize(650, 334)
        ProfileImportDialog.setMinimumSize(QtCore.QSize(650, 330))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        ProfileImportDialog.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(ProfileImportDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pb_Ok = StyledButton(parent=ProfileImportDialog)
        self.pb_Ok.setObjectName("pb_Ok")
        self.horizontalLayout.addWidget(self.pb_Ok)
        self.pb_Cancel = StyledButton(parent=ProfileImportDialog)
        self.pb_Cancel.setObjectName("pb_Cancel")
        self.horizontalLayout.addWidget(self.pb_Cancel)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(parent=ProfileImportDialog)
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 2)

        self.retranslateUi(ProfileImportDialog)
        QtCore.QMetaObject.connectSlotsByName(ProfileImportDialog)

    def retranslateUi(self, ProfileImportDialog):
        _translate = QtCore.QCoreApplication.translate
        ProfileImportDialog.setWindowTitle(_translate("ProfileImportDialog", "Profile Import"))
        self.pb_Ok.setText(_translate("ProfileImportDialog", "OK"))
        self.pb_Cancel.setText(_translate("ProfileImportDialog", "Cancel"))
from telemffb.custom_widgets import StyledButton
