# Form implementation generated from reading ui file 'profile_import_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ProfileImportDialog(object):
    def setupUi(self, ProfileImportDialog):
        ProfileImportDialog.setObjectName("ProfileImportDialog")
        ProfileImportDialog.resize(722, 460)
        ProfileImportDialog.setMinimumSize(QtCore.QSize(650, 330))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        ProfileImportDialog.setFont(font)
        self.gridLayout_2 = QtWidgets.QGridLayout(ProfileImportDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(parent=ProfileImportDialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.tableWidget.setFont(font)
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(parent=ProfileImportDialog)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.cb_importSim = QtWidgets.QCheckBox(parent=ProfileImportDialog)
        self.cb_importSim.setObjectName("cb_importSim")
        self.gridLayout.addWidget(self.cb_importSim, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.cb_importClass = QtWidgets.QCheckBox(parent=ProfileImportDialog)
        self.cb_importClass.setObjectName("cb_importClass")
        self.gridLayout.addWidget(self.cb_importClass, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(parent=ProfileImportDialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pb_Ok = StyledButton(parent=ProfileImportDialog)
        self.pb_Ok.setObjectName("pb_Ok")
        self.horizontalLayout.addWidget(self.pb_Ok)
        self.pb_Cancel = StyledButton(parent=ProfileImportDialog)
        self.pb_Cancel.setObjectName("pb_Cancel")
        self.horizontalLayout.addWidget(self.pb_Cancel)
        self.gridLayout_2.addLayout(self.horizontalLayout, 4, 0, 1, 1)

        self.retranslateUi(ProfileImportDialog)
        QtCore.QMetaObject.connectSlotsByName(ProfileImportDialog)

    def retranslateUi(self, ProfileImportDialog):
        _translate = QtCore.QCoreApplication.translate
        ProfileImportDialog.setWindowTitle(_translate("ProfileImportDialog", "Profile Import"))
        self.cb_importSim.setText(_translate("ProfileImportDialog", "Import Sim Defaults (Will overwrite any user sim default overrides for the sims of imported items)"))
        self.cb_importClass.setText(_translate("ProfileImportDialog", "Import Class Defaults (Will overwrite any user class default overrides for the classes of imported items)"))
        self.pb_Ok.setText(_translate("ProfileImportDialog", "OK"))
        self.pb_Cancel.setText(_translate("ProfileImportDialog", "Cancel"))
from telemffb.custom_widgets import StyledButton
