# Form implementation generated from reading ui file 'teleplot.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TeleplotDialog(object):
    def setupUi(self, TeleplotDialog):
        TeleplotDialog.setObjectName("TeleplotDialog")
        TeleplotDialog.resize(270, 392)
        self.layoutWidget = QtWidgets.QWidget(parent=TeleplotDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(7, 10, 263, 296))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.tb_port = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.tb_port.setObjectName("tb_port")
        self.gridLayout.addWidget(self.tb_port, 2, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.tb_vars = QtWidgets.QPlainTextEdit(parent=self.layoutWidget)
        self.tb_vars.setObjectName("tb_vars")
        self.gridLayout.addWidget(self.tb_vars, 6, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(parent=self.layoutWidget)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_6 = QtWidgets.QLabel(parent=self.splitter)
        self.label_6.setObjectName("label_6")
        self.pb_Select = QtWidgets.QPushButton(parent=self.splitter)
        self.pb_Select.setObjectName("pb_Select")
        self.gridLayout.addWidget(self.splitter, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=TeleplotDialog)
        self.label_5.setGeometry(QtCore.QRect(7, 310, 256, 26))
        self.label_5.setObjectName("label_5")
        self.layoutWidget1 = QtWidgets.QWidget(parent=TeleplotDialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 350, 251, 26))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_clear = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.pb_clear.setObjectName("pb_clear")
        self.horizontalLayout.addWidget(self.pb_clear, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.layoutWidget1)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox, 0, QtCore.Qt.AlignmentFlag.AlignRight)

        self.retranslateUi(TeleplotDialog)
        QtCore.QMetaObject.connectSlotsByName(TeleplotDialog)

    def retranslateUi(self, TeleplotDialog):
        _translate = QtCore.QCoreApplication.translate
        TeleplotDialog.setWindowTitle(_translate("TeleplotDialog", "Teleplot Setup"))
        self.label_4.setText(_translate("TeleplotDialog", "List:"))
        self.label_3.setText(_translate("TeleplotDialog", "Space separated list of Telemetry variables"))
        self.label_2.setText(_translate("TeleplotDialog", "Port:"))
        self.label.setText(_translate("TeleplotDialog", "Open a browser to teleplot.fr, record port number"))
        self.label_6.setText(_translate("TeleplotDialog", "or select from active: "))
        self.pb_Select.setText(_translate("TeleplotDialog", "Select..."))
        self.label_5.setText(_translate("TeleplotDialog", "To stop sending teleplot data,\n"
"clear the boxes and select OK"))
        self.pb_clear.setText(_translate("TeleplotDialog", "Clear"))
